server:
  port: 8080
  assets-path: /app/assets

theme:
  background-color: 240 8 9
  primary-color: 43 50 70
  contrast-multiplier: 1.0

pages:
  - name: Overview
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Europe/Brussels
                label: Home

          - type: weather
            units: metric
            hour-format: 24h
            location: Brussels, Belgium

      - size: full
        widgets:
          - type: server-stats
            title: Homelab server
            servers:
              - type: local
                name: Services
                hide-mountpoints-by-default: true

          - type: monitor
            title: Service Status
            cache: 30s
            sites:
              - title: Dockge
                url: http://192.168.1.10:5001
                icon: /assets/dockge.png
              - title: Glance
                url: http://192.168.1.10:8181
                icon: /assets/glance.png
              - title: qBittorrent
                icon: /assets/qbit.png
                url: http://192.168.1.10:8080
              - title: Radarr
                icon: /assets/radarr.png
                url: http://192.168.1.10:7878
              - title: Sonarr
                icon: /assets/sonarr.png
                url: http://192.168.1.10:8989
              - title: Prowlarr
                icon: /assets/prowlarr.png
                url: http://192.168.1.10:9696
              - title: Jellyfin
                icon: /assets/jellyfin.png
                url: http://192.168.1.10:8096
              - title: Plex
                icon: /assets/plex.png
                url: http://192.168.1.10:32400
              - title: FlareSolverr
                icon: /assets/flaresolverr.png
                url: http://192.168.1.10:8191

  - name: System
    columns:
      - size: full
        widgets:
          - type: docker-containers
            title: Docker containers
            sock-path: /var/run/docker.sock
