server:
  port: 8080
  assets-path: /app/assets

theme:
  background-color: 240 8 9
  primary-color: 43 50 70
  contrast-multiplier: 1.0

branding:
  app-name: Bakske
  hide-footer: true

pages:
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Europe/Brussels
                label: Home

          - type: server-stats
            title: Homelab server
            servers:
              - type: local
                name: Services
                hide-mountpoints-by-default: false

          - type: custom-api
            title: Gluetun status
            cache: 1m
            url: http://192.168.1.10:8000/v1/publicip/ip
            template: |
              {{ if eq .Response.StatusCode 200 }}
                {{ $ip := (.JSON.String "public_ip") }}
                {{ $city := (.JSON.String "city") }}
                {{ $country := (.JSON.String "country") }}
                {{ if eq $ip "" }}
                  <div>
                    <div>
                      <div>
                        <div class="color-highlight size-h3">
                          Your VPN is not connected!
                          <span class="color-negative">●</span> 
                        </div>
                      </div>
                    </div>
                  </div>
                {{ else }}
                  <div>
                    <div>
                      <div>
                        <div class="color-highlight size-h3">
                          Your VPN is connected!
                          <span class="color-positive">●</span> 
                        </div>
                      </div>
                      <div class="size-h5">{{ $ip }} - {{ $city }}, {{ $country }}</div>
                    </div>
                  </div>
                {{ end }}
              {{ else }}
                <div style="text-align: center; color: var(--color-negative);">
                  Error: {{ .Response.StatusCode }} - {{ .Response.Status }}
                </div>
              {{ end }}

          - type: monitor
            title: Media Stack
            cache: 30s
            sites:
              - title: qBittorrent
                icon: /assets/qbit.png
                url: http://192.168.1.10:8080
              - title: Radarr
                icon: /assets/radarr.png
                url: http://192.168.1.10:7878
              - title: Sonarr
                icon: /assets/sonarr.png
                url: http://192.168.1.10:8989
              - title: Prowlarr
                icon: /assets/prowlarr.png
                url: http://192.168.1.10:9696
              - title: FlareSolverr
                icon: /assets/flaresolverr.png
                url: http://192.168.1.10:8191
              - title: Bazarr
                icon: /assets/bazarr.png
                url: http://192.168.1.10:6767
              - title: Jellyfin
                icon: /assets/jellyfin.png
                url: http://192.168.1.10:8096
              - title: Plex
                icon: /assets/plex.png
                url: http://192.168.1.10:32400

      - type: monitor
         title: Monitor Stack
         cache: 30s
         sites:
           - title: Glance
              url: http://192.168.1.10:80
              icon: /assets/glance.png
           - title: Dockge
             url: http://192.168.1.10:5001
             icon: /assets/dockge.png

  - name: System
    columns:
      - size: full
        widgets:
          - type: docker-containers
            title: Docker containers
            sock-path: /var/run/docker.sock
