server:
  port: 8080
  assets-path: /app/assets

theme:
  background-color: 240 8 9
  primary-color: 43 50 70
  contrast-multiplier: 1.0

pages:
  - name: Overview
    columns:
      - size: full
        widgets:
          - type: bookmarks
            groups:
              - title: Homelab Services
                links:
                  - title: Dockge
                    url: http://192.168.1.10:5001
                    icon: /assets/dockge.png
                  - title: Glance
                    url: http://192.168.1.10:8181
                    icon: /assets/glance.png
                  - title: qBittorrent
                    url: http://192.168.1.10:8080
                    icon: /assets/qbit.png
                  - title: Radarr
                    url: http://192.168.1.10:7878
                    icon: /assets/radarr.png
                  - title: Sonarr
                    url: http://192.168.1.10:8989
                    icon: /assets/sonarr.png
                  - title: Prowlarr
                    url: http://192.168.1.10:9696
                    icon: /assets/prowlarr.png
                  - title: Jellyfin
                    url: http://192.168.1.10:8096
                    icon: /assets/jellyfin.png
                  - title: Plex
                    url: http://192.168.1.10:32400
                    icon: /assets/plex.png
                  - title: FlareSolverr
                    url: http://192.168.1.10:8191
                    icon: /assets/flaresolverr.png

          - type: monitor
            title: Service Status
            cache: 30s
            sites:
              - title: Dockge
                url: http://192.168.1.10:5001
                icon: /assets/dockge.png
              - title: Glance
                url: http://192.168.1.10:8181
                icon: /assets/glance.png
              - title: qBittorrent
                url: http://192.168.1.10:8080
                icon: /assets/qbit.png
              - title: Radarr
                url: http://192.168.1.10:7878
                icon: /assets/radarr.png
              - title: Sonarr
                url: http://192.168.1.10:8989
                icon: /assets/sonarr.png
              - title: Prowlarr
                url: http://192.168.1.10:9696
                icon: /assets/prowlarr.png
              - title: Jellyfin
                url: http://192.168.1.10:8096
                icon: /assets/jellyfin.png
              - title: Plex
                url: http://192.168.1.10:32400
                icon: /assets/plex.png
              - title: FlareSolverr
                url: http://192.168.1.10:8191
                icon: /assets/flaresolverr.png

  - name: System
    columns:
      - size: full
        widgets:
          - type: docker-containers
            title: Docker containers
            sock-path: /var/run/docker.sock
