services:
  app:
    image: torando/expense-tracker:latest
    container_name: expense-tracker
    environment:
      - NODE_ENV=production
    ports:
      - '4173:4173'
    volumes:
      - ./app/sqlite.db:/app/sqlite.db
      - ./app/data:/app/data
    restart: unless-stopped